name: Void FPS Boost - Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Gradle 8.9
        shell: bash
        run: |
          set -e

          wget -q https://services.gradle.org/distributions/gradle-8.9-bin.zip

          sudo mkdir -p /opt/gradle

          sudo unzip -q gradle-8.9-bin.zip -d /opt/gradle

          echo "/opt/gradle/gradle-8.9/bin" >> "$GITHUB_PATH"

          gradle --version

      - name: Find
